version: "3.9"

services:
  db:
    image: postgres:13
    restart: always
    container_name: integration-tests-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: tests